@baseUrl = http://localhost:3000

### Read all films
GET {{baseUrl}}/films

### Read a specific film with his id
GET {{baseUrl}}/films/8

### Get all film which have a duration above the minimum duration
GET {{baseUrl}}/films?minimum-duration=170

### Create a new film
POST {{baseUrl}}/films
Content-Type: application/json

{
    "title": "b",
    "director": "bonjour",
    "duration": 154,
    "budget": 1500
}

### Get a film if the caracter specified in the query match with caracter in the title

GET {{baseUrl}}/films?caracter-chaine=Ince

### Delete an element in the film list
DELETE {{baseUrl}}/films/8

### Update the film identified by 5
PATCH {{baseUrl}}/films/5
Content-Type: application/json

{
    "title":"test0"
}

### We change all the informations that we put in the body
PUT {{baseUrl}}/films/5
Content-Type: application/json

{
    "title": "test1"
}